### ISSUE TITLE
Link between editor window and CMap appears to have been lost

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RuleWorld/rulebender#148]
```
Clicking on a molecule or component in the CMap used to result in information 
about that entity appearing in the 'Properties' tab. As of revision 277 this no 
longer is the case.
```

Original issue reported on code.google.com by `lh64@cornell.edu` on 17 Aug 2013 at 6:34

**Comment by rhclark** [comment]
In version 2.1.0-testing, these issues should now be resolved.  Feel free to open additional issues if you find that problems remain.
