### ISSUE TITLE
In models with multiple syntax errors, often only the first one is highlighted

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RuleWorld/rulebender#152]
```
It might be useful to highlight all errors rather than just the first one. Not 
sure if this is possible in the RCP framework or not.
```

Original issue reported on code.google.com by `lh64@cornell.edu` on 14 Oct 2013 at 7:08

**Comment by rhclark** [comment]
This has been fixed in version 2.1.0-testing of RuleBender.  Feel free to open other issues if you feel the problems remain.
