### ISSUE TITLE
Default setting of simulator path

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RuleWorld/rulebender#153]
```
We're starting to see issues where people download new versions of RB and don't 
realize that the simulator path is still set to the older version of BioNetGen 
from the previous RB installation. They obviously don't get any error message 
that the path isn't set because it is, although erroneously. Having the 
simulator path set automatically would alleviate this problem.
```

Original issue reported on code.google.com by `lh64@cornell.edu` on 17 Oct 2013 at 8:45

**Comment by rhclark** [comment]
Hmmmm.....   This is interesting.  This can certainly be resolved, but we should talk a bit about the user interface.

**Comment by rhclark** [comment]
I wonder if we should have a file in the RuleBender directory that acts as a flag.  If the file is there, it means that RuleBender has just been installed and has not yet been run.  Then when RuleBender is run for the first time, it uses the newly installed version of BioNetGen, sets the simulator path appropriately, and deletes the flag file.  Thereafter, when RuleBender is run, it will not reset the simulator path, as long as the simulator path is pointing to some valid version of BioNetGen.

**Comment by jrfaeder** [comment]
I think this was implemented and one no longer has to set the path on a new installation.
