### ISSUE TITLE
Update  RB-README.txt, LICENSE.txt and CREDITS.txt

### ISSUE THREAD

**Issue by rhclark** [RuleWorld/rulebender#160]
We should probably update the RB-README.txt, LICENSE.txt and CREDITS.txt files.

**Comment by jjtapia** [comment]
Update the about message inside Window->About:
-----
RuleBender 2.1.0

RuleBender was developed in collaboration between the groups of Dr. James R. Faeder and Dr. Elisabeta G. Marai at the University of Pittsburgh. It is currently maintained by the Faeder Lab in the Department of Computational and Systems Biology, School of Medicine, University of Pittsburgh.

Major Contributors:
Adam M. Smith (Marai Lab)
Wen Xu (Marai Lab)
John Wenskovitch (Marai Lab)
Yao Sun (Marai Lab)
Robert Engelke (Faeder Lab)
Leonard Harris (Faeder Lab)

Current Developers:
Robert Clark (Faeder Lab)
Jose Juan Tapia (Faeder Lab)

**Comment by rhclark** [comment]
Done
