### ISSUE TITLE
Small multiples view doesn't offer the option to remove syn/deg/transformation petri net nodes

### ISSUE THREAD

**Issue by jjtapia** [RuleWorld/rulebender#164]
Unlike the contact map view,the small multiples /MOSBIE visualization doesn't offer this option, which can potentially result in very cluttered visualizations

![screenshot from 2015-07-21 20 52 09](https://cloud.githubusercontent.com/assets/4514041/8815687/a030bc9e-2fea-11e5-9b1f-d6ee25912d1e.png)

**Comment by rhclark** [comment]
Hi Jose,  I looked at the code for the contact map, and I didn't see anything for the removal of syn/deg/transformation petri net nodes.  Maybe I just didn't look hard enough.

Could you describe the procedure that you use in the Contact map to identify the sub-graph that you wanto eliminate?  (Or is the sub-graph defined implicitly by the hilighting in the BNG editor ?)

**Comment by jjtapia** [comment]
The functionality I'm refering to is that when you right click on the contact map, an option called Hide syn/deg appears. This option removes the petri net nodes and edges that refer to these kind of transformations. These option is missing from the MOSBIE interface.
