### ISSUE TITLE
BNGL parser needs to be updated with PLA options

### ISSUE THREAD

**Issue by jjtapia** [RuleWorld/rulebender#170]
It is also showing some problems in the Creamer model

**Comment by lh64** [comment]
Which options aren't supported in the parser? Can you include an example model? I added support for 'pla' as an option for 'method' in 'simulate', as well as 'pla_config' and 'pla_output'. 'pla_config' just takes any sequence of characters though, it doesn't actually parse the arguments.

**Comment by jjtapia** [comment]
I wonder if I was using an older version of the parser. The tests on the bnglparser test suite are all passing, and looking at the existing grammar definitions it seems to match to what the options should be. I'll close this issue for now.
