### ISSUE TITLE
Reading a  .bngl  file with errors in it, causes a traceback.

### ISSUE THREAD

**Issue by rhclark** [RuleWorld/rulebender#179]
These errors seem to be non-fatal, but when you read in a  .bngl  file with an error in it, you often get a traceback.  You also sometimes get a dialogue box indicating that there was a problem, but no clue is given about what the problem was.   It would be good to get rid of the tracebacks, and possibly generate a dialog box that points the user to a problem in the file.

**Comment by jrfaeder** [comment]
This was a generic issue. I'm opening a more specific one concerning line labels and indices.
