### ISSUE TITLE
BNG Root Path isn't remembered as default

### ISSUE THREAD

**Issue by ryants** [RuleWorld/rulebender#193]
I have to manually select my BNG root path every time I open Rulebender (Defaults to No_Valid_Path).  The root path is remembered in the drop-down menu, but doesn't get pushed to the default path the next time RB is opened

Minor, but annoying

**Comment by rhclark** [comment]
Hi Ryan,

         Thanks very much for reporting the problem.   You're right that that's how it should work, and if you've got a little bit of time, I'd like to try and figure out why it's failing for you.  

          Could you do a run where you do the following:

./RuleBender > out.txt                    (This command might look a bit different for Windows or
                                                               Macintosh.  Feel free to get back to me if this does not
                                                               work for you.)
In RuleBender, do:    Window->Preferences->Settings->Maximal Output
In RuleBender, do something (like a simulation) that requires BioNetGen
Close RuleBender
Send me the   out.txt   file.

I'm not sure whether this will give me all the information that I need, but it should be a good starting point for fixing the problem.   Thanks a lot !!    --  Rob Clark

**Comment by rhclark** [comment]
Oops.....   I didn't mean to close the issue ....

**Comment by rhclark** [comment]
Feel free to send output to   roc60@pitt.edu

**Comment by rhclark** [comment]
Another simple thing occured to me.  You may need to click on "Remember All BioNetGen Directories" in the "Switch Workspace" dialogue box.  --  Rob Clark

**Comment by ryants** [comment]
I do have the "remember all bng directories" box checked!  I'll get you that other info shortly.  Also, in case it's relevant, I'm on Ubuntu 12.04

**Comment by rhclark** [comment]
Hi Ryan,
         Thanks for sending the output.  I see that your Java version is 1.6, and we have a requirement for Java 1.7.   In fact, the very latest beta version of RuleBender has an explicit check for Java 1.7, and it puts up a dialogue box to warn the user if it's not there.

          Can you update your Java version ?   I did a quick search on the web to get instructions, and I see that there are instructions that are specifically for Ubuntu.

          Upgrading the Java version should also eliminate the Java tracebacks that you see in the output.  Your version of Ubuntu is a little bit older than mine, but I don't think that that should be a problem.

           Thanks for your help, and feel free to get back to me if you have other questions !!

Rob Clark

**Comment by rhclark** [comment]
RuleBender version  2.1.0.4 has a fix for the problem that it does not remember the BioNetGen location by default.  Since the issues here seem to be resolved, I'm going to close this defect.  Feel free to open another defect if I'm wrong.
