### ISSUE TITLE
Bill Hlavacek's  Species Graph Bug

### ISSUE THREAD

**Issue by rhclark** [RuleWorld/rulebender#196]
This defect actually had two parts.  There was a problem with BioNetGen, which I believe has been fixed.  But it was also noted that BioNetGen was able to generate the various result files that are needed to generate the density graph and so on despite the fact that it had encountered a problem during simulation.  It seems wrong that RuleBender should die, before generating the graphs, and that's exactly what was happening.

The code that causes this is in  BNGExecutionJob.java, and there may be similar code elsewhere.  It's not hard to find the spot where RuleBender dies, and it's not hard to find the spot where the DensityGraph should get generated.   I guess that what's needed is to carefully reshuffle the logic a bit, so that the DensityGraph is generated and then BioNetGen dies gracefully.

The model file that causes the problem is attached.  GitHub wouldn't let me upload a  .bngl  file, so I converted the filetype to .txt
[bug_states_break_RB_plotting.txt](https://github.com/RuleWorld/rulebender/files/443192/bug_states_break_RB_plotting.txt)

**Comment by jrfaeder** [comment]
Seems to be resolved.
