### ISSUE TITLE
Parameter expression bug

### ISSUE THREAD

**Issue by jrfaeder** [RuleWorld/rulebender#201]
If you use an undefined parameter in an expression that is used in a rule, RB hangs. This bug is particularly irritating because RB will hang again upon restart until the problem file is removed from the workspace, which has to be done manually outside of RuleBender. I've attached a simple example that illustrates the problem.

[template.bngl.txt](https://github.com/RuleWorld/rulebender/files/944381/template.bngl.txt)

**Comment by rhclark** [comment]
When defect  4b56994  is built, this should be fixed.

**Comment by jrfaeder** [comment]
This is now resolved. RB throws an error, but when that is fixed the contact map is displayed and the model can be used normally.
