### ISSUE TITLE
Cannot get past pick workspace dialog, os x 10.11

### ISSUE THREAD

**Issue by inwit-info** [RuleWorld/rulebender#204]
Hello
On the first launch of RuleBender it asks for workspace location. However on my mac 10.11 this dialog does not react in any way on clicks or pressing enter, tab or space. I can drag the window but cannot close it or confirm workspace location.
What is the best way to go past it? Should I include any particular diagnostics?

Rulebender version is 2.2.1

**Comment by jrfaeder** [comment]
This problem occurs when RB is run using JRE's later than 1.8.0_151. To address this problem we included this JRE in the RuleBender release that is currently posted on the website. It is not clear what is causing this incompatibility with recent JRE releases, and we will try to address the problem in future releases.
