### ISSUE TITLE
Help: An error has occured. See the log file.

### ISSUE THREAD

**Issue by Susana465** [RuleWorld/rulebender#220]
Hello,

I have tried to open RuleBender this morning in my Ubuntu (18.04) and it does now work.

![error_rulebender](https://user-images.githubusercontent.com/73224467/106450491-2a66c580-647d-11eb-988b-aa75e9927550.png)

It was working fine on Friday, and I have not changed anything since then. So not really sure what might have happened here?

Here is what the log file looks like.

Any help would be much appreciated.

[.log](https://github.com/RuleWorld/rulebender/files/5903560/default.log)

**Comment by Susana465** [comment]
I will add this: I exited RuleBender without saving changes and I have the feeling is what is causing it to crash now...but I am unsure as how to fix it.

I attach here what I see in the command line (but I have to say my background is not computer science so these look a bit like foreign language to me). Perhaps it helps sleuth how to fix it?
![ERROR5](https://user-images.githubusercontent.com/73224467/106451463-85e58300-647e-11eb-9289-1d7f4665ac6c.png)
![ERROR4](https://user-images.githubusercontent.com/73224467/106451470-867e1980-647e-11eb-9d19-cde8c3dc4768.png)
![ERROR3](https://user-images.githubusercontent.com/73224467/106451472-8716b000-647e-11eb-9c0f-45d9960bba06.png)
![ERROR2](https://user-images.githubusercontent.com/73224467/106451475-87af4680-647e-11eb-8f96-690fca050f0c.png)
![ERROR1](https://user-images.githubusercontent.com/73224467/106451477-8847dd00-647e-11eb-94a9-a1734fef2345.png)

**Comment by ASinanSaglam** [comment]
Hi Susana, 

Can you try moving the ```.metadata``` folder out of ```RuleBender-workspace``` folder and try opening it again? See if that lets you start it again.

**Comment by Susana465** [comment]
Hi, 

Thank you for the fast reply Ali, that worked :)

**Comment by ASinanSaglam** [comment]
Great to hear and you are welcome! 

You might lose some of the settings that are saved but everything else should be fine. Please let me know if you notice something important is missing, until then I'll close the issue.
